### ISSUE TITLE
Sprite animation preview cause crash

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-bugs#6820]
## Problem description

Sprite preview property cause crash when turn off in editor.

## Attach a .c3p

https://mega.nz/file/FZkASKAK#a0SXvsoJuYGFGcCXCgon88h5ha2B6ncKUPtSSgMula8

## Steps to reproduce

1. Create Sprite
2. Add frames to Sprite
3. Check preview checkbox in Sprite's properties
4. Uncheck preview checkbox in Sprite's properties
5. Crash

## Observed result

Crash

## Expected result

Turn off preview.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r335/plugins/allEditorPlugins.js, line 220, col 257
Message: Uncaught TypeError: Cannot read properties of null (reading 'Aw')
Stack: TypeError: Cannot read properties of null (reading 'Aw') at window.Knb.wv [as zx] (https://editor.construct.net/r335/plugins/allEditorPlugins.js:220:257) at d.tX (https://editor.construct.net/r335/projectResources.js:813:216) at d.IYa (https://editor.construct.net/r335/projectResources.js:815:460) at d.cXb (https://editor.construct.net/r335/projectResources.js:822:463) at d.Mi (https://editor.construct.net/r335/projectResources.js:822:211) at d.tk (https://editor.construct.net/r335/projectResources.js:823:169) at d.Avc (https://editor.construct.net/r335/projectResources.js:841:467) at d.Wf (https://editor.construct.net/r335/projectResources.js:1371:376) at d.Wf (https://editor.construct.net/r335/projectResources.js:1328:324) at f6b (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:89:317)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Wed Mar 22 2023 14:35:04 GMT+0100 (közép-európai téli idő)
Uptime: 94.9 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.65
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6818
