### ISSUE TITLE
Crash when previewing animation

### ISSUE THREAD

**Issue by SimplyChark** [Scirra/Construct-bugs#6824]
The engine crashes when previewing any animation on macOS. 

## Attach a .c3p

[Whoops.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11053482/Whoops.c3p.zip)

## Steps to reproduce

1. Create new sprite object
2. Create a 5 frame animation
3. Close screen
4. Press preview
5. Wait

## Observed result

The engine crashed

## Expected result

The engine not crashing and showing me the preview

## More details

**Affected browsers/platforms:** Chrome, MacOs

**First affected release:** Only tested in r335 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r335/plugins/allEditorPlugins.js, line 220, col 257
Message: Uncaught TypeError: Cannot read properties of null (reading 'Aw')
Stack: TypeError: Cannot read properties of null (reading 'Aw') at window.Knb.wv [as zx] (https://editor.construct.net/r335/plugins/allEditorPlugins.js:220:257) at d.Hv (https://editor.construct.net/r335/projectResources.js:813:34) at d.jQb (https://editor.construct.net/r335/projectResources.js:844:23) at Ubb.jQ (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:208:475) at Ubb.hD (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:203:195) at window.Pl.dispatchEvent (https://editor.construct.net/r335/main.js:1234:42) at f6b (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:91:459)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Thu Mar 23 2023 19:41:51 GMT+0300 (GMT+03:00)
Uptime: 139.7 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 109.0.5414.87
Browser engine: Chromium
Context: browser
Operating system: macOS 13.1.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M2, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by SimplyChark** [comment]
I think this has already been asked so I will close it I think.
