### ISSUE TITLE
Crash amogus hide global layers :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6912]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_amogus_hide_global_layers_r337_2b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11216300/crash_amogus_hide_global_layers_r337_2b.zip)

## Steps to reproduce

1. Open a project.
2. Select the sprite.
3. Rename `Layer 0` to `Layer 1`.
4. Click on the selection point.
5. In the left ear, change the value of the `Layer` parameter to `Layer 0`.

## Observed result

https://user-images.githubusercontent.com/91274932/231593027-322c8354-a41b-4c60-9a27-6c4b7dd0edc0.mp4

## Expected result

Construct does not crash.

## More details

https://user-images.githubusercontent.com/91274932/231597185-d7b40d80-56de-4bfd-a187-12db7c5ca8a7.mp4

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r337-2b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r337-2/projectResources.js, line 1368, col 365
Message: Uncaught Error: instance not on this layer
Stack: Error: instance not on this layer at d.Gpc (https://editor.construct.net/r337-2/projectResources.js:1368:371) at d.xkb (https://editor.construct.net/r337-2/projectResources.js:818:477) at https://editor.construct.net/r337-2/components/bars/propertiesBar/propertiesBar.js:18:424 at bh (https://editor.construct.net/r337-2/main.js:371:492) at wq.g.K.ofb.RT (https://editor.construct.net/r337-2/main.js:1532:418) at wq.g.K.ofb.kG (https://editor.construct.net/r337-2/main.js:1533:71) at HTMLSelectElement.Ws (https://editor.construct.net/r337-2/main.js:1531:343)
Construct version: r337.2
URL: https://editor.construct.net/r337-2/
Date: Thu Apr 13 2023 00:19:42 GMT+0300 (Восточная Европа, летнее время)
Uptime: 665.5 s

Platform information
Product: Construct 3 r337.2 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
