### ISSUE TITLE
tileMovement no instance errror and black screen

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6989]
## Problem description
creating an object with the tileMovement behavior that has no instance in any layout causes an error and black screen.
(My guess is a default value to fall back to is missing)

## Attach a .c3p
[noInstanceTileMovement.zip](https://github.com/Scirra/Construct-bugs/files/11344145/noInstanceTileMovement.zip)

## Steps to reproduce

1. start preview
2. press f12

## Observed result
Black screen and error message:
caught (in promise) TypeError: Cannot read properties of null (reading '6')
    at new TileMovementInstance (runtime.js:4:131)
    at C3.New (jsutil.js:16:47)
    at BehaviorInstance._CreateSdkInstance (behaviorInstance.js:3:208)
    at Instance._CreateSdkInstance (instance.js:7:108)
    at C3Runtime.CreateInstanceFromData (runtime.js:58:349)
    at C3Runtime.CreateInstance (runtime.js:51:390)
    at SystemPlugin.CreateObject (runtime.js:51:353)
    at Action._RunSystem (action.js:21:339)
    at EventBlock._RunActions_Fast (eventBlock.js:26:97)
    at EventBlock._RunAndBlock (eventBlock.js:24:220)

## Expected result
no error and preview work

## More details

it seems to work fine with other behaviors, I could only find this issue with tile movement

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
