### ISSUE TITLE
webGPU PlatformInfo.RenderDetail Error

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6995]
## Problem description
getting PlatformInfo.RenderDetail causes an error when using webGPU

## Attach a .c3p
[webGPUrendererInfo.zip](https://github.com/Scirra/Construct-bugs/files/11361660/webGPUrendererInfo.zip)

## Steps to reproduce

1. run preview with webGPU
2. press f12

## Observed result
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetUnmaskedRenderer')
    at PlatformInfoInstance.RendererDetail (runtime.js:9:339)
    at ExpressionParameter._expressionFunc (expFuncs.js:99:17)
    at ExpressionParameter.GetExpression (parameter.js:6:340)
    at Condition.RunSingleCnd_3params [as Run] (condition.js:9:454)
    at EventBlock._RunAndBlock (eventBlock.js:24:127)
    at EventBlock.Run (eventBlock.js:21:212)
    at EventSheet.Run (eventSheet.js:10:511)
    at EventSheetManager.RunEvents (eventSheetManager.js:13:76)
    at C3Runtime.Step_RunEventsEtc (runtime.js:82:304)
    at C3Runtime.Tick (runtime.js:78:317)

## Expected result
no error

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
