### ISSUE TITLE
C3 Error

### ISSUE THREAD

**Issue by Trullybug** [Scirra/Construct-bugs#7009]
## Problem description

When I open the game, it freezes out of nowhere and I automatically get this mysterious error.

## The .c3p

https://we.tl/t-8f4kkT0HPf

## Observed result

the game and engine crashes when trying to view the layout. Then when I try to open c3p it won't let me.

## Expected result

the result I expect is that it will let me open the .c3p again

## More details

**Affected browsers/platforms:** Chrome.

**First affected release:** r336.

## System details

Error report information
Type: assertion failure
Message: cannot find 'Texto' object class index
Stack: Error at qa.bXa (https://editor.construct.net/r336/main.js:1104:289) at window.assert (https://editor.construct.net/r336/main.js:1019:353) at d.gP (https://editor.construct.net/r336/projectResources.js:3072:405) at d.bc (https://editor.construct.net/r336/projectResources.js:797:184) at d.bc (https://editor.construct.net/r336/projectResources.js:854:504) at https://editor.construct.net/r336/projectResources.js:1374:495 at Array.map () at d.bc (https://editor.construct.net/r336/projectResources.js:1374:486) at https://editor.construct.net/r336/projectResources.js:1331:411 at Array.map ()
Construct version: r336
URL: https://editor.construct.net/
Date: Sun May 07 2023 11:05:00 GMT-0500 (hora estándar de Perú)
Uptime: 51508.7 s

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.138
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: es-ES

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Plus Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by WilsonPercival** [comment]
@Trullybug You provided a project file that is already broken.

Could you provide a project file that can open and cause the crash?

**Comment by Trullybug** [comment]
I'm afraid not, I have an older version, but now it won't let me open it either. Before there was an option in Construct 3 that indicated the problem, too bad.

However, I can send you an older version, although it doesn't open either...
https://we.tl/t-bSTvsDGAnr

**Comment by GameSoul7Eugene** [comment]
@Trullybug, I fixed your project, so now it should open successfully: [Download link](https://drive.google.com/file/d/1V7x8LnwCUPQLcxuDHG2k0wy4uA21SEol/view?usp=share_link)

**Comment by AshleyScirra** [comment]
The provided project doesn't open as it appears to be corrupt (the console logs "Error: cannot find object type named 'GameDead'"). I'd suggest restoring a backup or using the restored project link provided previously.

Unfortunately without steps to reproduce the original cause for this, there's no way to know how it happened or do anything further to fix it, so closing. If you can find steps that reliably cause this to happen please do file an issue and it would be a high priority for us to fix.
