### ISSUE TITLE
Uncaught (in promise) crash r350

### ISSUE THREAD

**Issue by Fengist** [Scirra/Construct-bugs#7215]
## Problem description

c3runtime.js:400 Uncaught (in promise) TypeError: Type is not a constructor
    at C3.New (c3runtime.js:400:47)
    at PluginManager.CreatePlugin (c3runtime.js:3083:467)
    at C3Runtime._LoadDataJson (c3runtime.js:3574:448)
    at C3Runtime.Init (c3runtime.js:3565:462)
    at async InitRuntime (workermain.js:8:1)
    
        C3.New = function New(Type, ...args) {
        let o;
        try {
            o = new Type(...args)  <---------------------------
        } catch (e) {
            ctorProxyToObject.clear();
            ctorObjectToProxy.clear();
            throw e;
        }
        if (C3.isDebugDefend)
            VerifyObjectPropertiesConsistent(Type, o);
        return C3.debugDefend(o)
    }

## Attach a .c3p

https://drive.google.com/file/d/1d7hJ_R5ABlaUk7s_RqnB08DduNmRPebp/view?usp=drive_link

## Steps to reproduce

1. Export to HTML5
2. Upload to Server
3. Run in Chrome

## Observed result

Crash

## Expected result

Not Crash

**Affected browsers/platforms:** 

Chrome Version 114.0.5735.199 (Official Build) (64-bit)
(Attempted restart of browser, CTL-R and F5)

Works properly in Edge Version 114.0.1823.82 (Official build) (64-bit)

**First affected release:** 
r350

**Comment by WilsonPercival** [comment]
@Fengist Can not reproduce. Everything works well for me.

<img width="934" alt="observed" src="https://github.com/Scirra/Construct-bugs/assets/91274932/e34c4d52-0e2d-41e9-b6f0-a6341d39558c">

**Comment by Fengist** [comment]
> @Fengist Can not reproduce. Everything works well for me.
> 
> <img alt="observed" width="934" src="https://user-images.githubusercontent.com/91274932/253762526-e34c4d52-0e2d-41e9-b6f0-a6341d39558c.png">

Here's the URL where I uploaded the contentents of the .zip

https://twistedvoid.com/C3/Hacking/

**Comment by AshleyScirra** [comment]
The provided URL works fine for me in Chrome. There is no error loading it.

Try disabling any browser extensions you have - sometimes they can interfere with web pages working properly.
