### ISSUE TITLE
Crash when using InOutSinusoidal tween with 0 Time

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7249]
## Problem description
Calling Tween with Ease=InOutSinusoidal for 0 seconds causes the game to crash.

## Attach a .c3p
[tween.zip](https://github.com/Scirra/Construct-bugs/files/12147238/tween.zip)

## Steps to reproduce

1. Click button
2. Check browser console

## Observed result
Game crashes, and shows exception.

## Expected result
Tween immedaitely

## More details

**Affected browsers/platforms:** 

**First affected release:** r350 stable

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'GetNext')
    at Transition.Interpolate (transition.js:6:347)
    at ease.js:30:19
    at NumericTypeAdapter.Interpolate (numericTypeAdapter.js:5:237)
    at PropertySourceAdapter.Interpolate (propertySourceAdapter.js:4:23)
    at TweenPropertyTrackState.Interpolate (tweenPropertyTrackState.js:4:189)
    at TweenTrack.Interpolate (tweenTrackState.js:6:134)
    at TweenTrack.SetInitialState (tweenTrackState.js:5:112)
    at Tween.SetInitialState (timelineState.js:22:490)
    at Tween.SetInitialState (tweenState.js:10:454)
    at TimelineManager._OnTick (timelineManager.js:18:179)

</details>

**Comment by WilsonPercival** [comment]
https://github.com/Scirra/Construct-bugs/issues/6916

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta along with #6916 which was a similar issue.
