### ISSUE TITLE
 r346 some timeline spritefont properties crash runtime

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-bugs#7323]
## Problem description

Using next spritefont properties in timeline will lead to crash during runtime and will not appear during timeline preview:
- Scale
- Character spacing
- Line height

## Attach a .c3p

[spritefont-scale-timeline-bug.zip](https://github.com/Scirra/Construct-bugs/files/12418592/spritefont-scale-timeline-bug.zip)

## Steps to reproduce

1. Add timeline
2. Use spritefont properties from above

## Observed result

Spritefont propertirs don't work

## Expected result

Spritefont properties work

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r346

## System details

<details><summary>Runtime error</summary>

Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not an object
    at PluginSourceAdapter.GetOptionalCallbacks (pluginSourceAdapter.js:4:11)
    at NumericInterpolationAdapter._Setter (numericInterpolationAdapter.js:35:283)
    at NumericInterpolationAdapterForTimeline.ChangeProperty (numericInterpolationAdapterForTimeline.js:5:176)
    at NumericInterpolationAdapter.ChangeProperty (numericInterpolationAdapter.js:33:179)
    at PluginSourceAdapter.Interpolate (propertySourceAdapter.js:4:478)
    at PluginSourceAdapter.Interpolate (pluginSourceAdapter.js:3:48)
    at PropertyTrack.Interpolate (propertyTrackState.js:14:267)
    at Track.Interpolate (trackState.js:21:31)
    at Track.SetInitialState (trackState.js:17:141)
    at Timeline.SetInitialState (timelineState.js:22:490)

</details>

**Comment by WilsonPercival** [comment]
@elfwy-uwu Could you write steps to reproduce the problem?

**Comment by elfwy-uwu** [comment]
@WilsonPercival my cat published an empty issue, sorry

**Comment by AshleyScirra** [comment]
I fixed the crash at runtime so it should show correctly there in the next beta. However assigning to @DiegoScirra to investigate why those properties don't preview in the editor.
