### ISSUE TITLE
Array editor crashes when changing array's width or height

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#7328]
## Problem description

Array editor crashes when changing array's Width or Height. Changing Depth or Sheet is ok.

## Attach a .c3p

[ArrayEditorBug.zip](https://github.com/Scirra/Construct-bugs/files/12420316/ArrayEditorBug.zip)

## Steps to reproduce

1. Open "New Array.json" in Array editor
2. Change Width or Height

## Observed result

Editor Crashes

## Expected result

Not to crash

## More details

**Affected browsers/platforms:** Chrome Windows

**First affected release:** 355

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js, line 102, col 287
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Pa')
Stack: TypeError: Cannot read properties of undefined (reading 'Pa') at Qpb.Rkc.Dg (https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:102:287) at d.Yxb (https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:38:267) at Array. (https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:23:358) at CCG.Qh.g.hb.dispatchEvent (https://editor.construct.net/r355/main.js:1257:42) at HTMLInputElement.uGb (https://editor.construct.net/r355/main.js:1743:486)
Construct version: r355
URL: https://editor.construct.net/r355/
Date: Wed Aug 23 2023 17:25:34 GMT+0300 (Θερινή ώρα Ανατολικής Ευρώπης)
Uptime: 26.5 s

Platform information
Product: Construct 3 r355 (beta)
Browser: Chrome 116.0.5845.97
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by AshleyScirra** [comment]
Oops, this is an accidental regression in r355 after making other changes to improve usability. Thanks for spotting, should be fixed in the next beta.

**Comment by AshleyScirra** [comment]
Leaving open and marked fix to try to prevent further duplicates being filed.
