### ISSUE TITLE
Error during Andorid export

### ISSUE THREAD

**Issue by diamond-cher** [Scirra/Construct-bugs#7464]
## Problem description

When I try to export android build (debug apk), I see this error. But export is continue. 

## Attach a .c3p

I can't attach a .c3p because it is my game, and it is weight >25 MB.

## Steps to reproduce

1. Open export menu
2. Choose Android (Cordova)
3. Check deduplicate img and recompression img
4. Next
5. Choose Android build as Debug apk (Min version 7.0+)
6. Next
7. Error

## Observed result

Error screen and continue to export.
![n4IWukqkdN](https://github.com/Scirra/Construct-bugs/assets/46075980/d72a8561-901d-4652-b507-6fc74d7f106c)

## Expected result

Export without error screen.

## More details

Affected browsers/platforms: Edge, Android

**First affected release: r358

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r358/main.js, line 1917, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at rr.g.ki.NLa (https://editor.construct.net/r358/main.js:1917:242) at aj.g.avc.zd (https://editor.construct.net/r358/main.js:1919:416) at https://editor.construct.net/r358/main.js:1919:139
Construct version: r358
URL: https://editor.construct.net/
Date: Sun Oct 15 2023 16:09:49 GMT+0200 (Central European Summer Time)
Uptime: 11100.1 s

Platform information
Product: Construct 3 r358 (stable)
Browser: Edge 117.0.2045.60
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
Language setting: ru-RU

WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: intel
Adapter architecture: gen-12lp
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features: bgra8unorm-storage, depth-clip-control, depth32float-stencil8, indirect-first-instance, rg11b10ufloat-renderable, texture-compression-bc

</details>

**Comment by WilsonPercival** [comment]
@diamond-cher Can you upload your project to any free file hosting service, such as Dropbox?

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the guidelines. As they say, please provide a minimal project which reproduces the issue, which does not have to be your full project.

The error looks like it may be caused by a browser extension interfering with Construct, so try disabling any browser extensions you have.
