### ISSUE TITLE
Music with effect stops on game load

### ISSUE THREAD

**Issue by johnBrink** [Scirra/Construct-bugs#7625]
## Problem description

Whenever I save and load my game's state while audio is playing with an effect, the music will abruptly stop. This happens in a function related to reloading  My Audio object is set to "Save/load: None" so it seems like it shouldn't be trying to load anything anyway.

## Attach a .c3p

[Audio effect load bug.zip](https://github.com/Scirra/Construct-bugs/files/13594979/Audio.effect.load.bug.zip)

## Steps to reproduce

1. Press Play music
2. Press Add filter
3. Press Save state
4. Press Load state

## Observed result

The music stops playing.

## Expected result

The music keeps playing without interruption.

## More details
I get this error in the console:

```
domSide.js:33 Uncaught (in promise) TypeError: tags is not iterable
    at AudioDOMHandler._AddEffect (domSide.js:33:501)
    at domSide.js:40:272
    at Array.map (<anonymous>)
    at AudioDOMHandler._OnLoadState (domSide.js:40:260)
    at domSide.js:5:261
    at RuntimeInterface._OnEventFromRuntime (domSide.js:33:348)
    at RuntimeInterface._OnMessageFromRuntime (domSide.js:32:98)
    at _messageChannelPort.onmessage (domSide.js:14:384)
```

Also, within the `_AddEffect()` function, I see that the `e` variable has a `tag` property of `"BGM"`, where the function expects it to have a `tags` property containing an array.

**Affected browsers/platforms:** Tested on Chrome, Windows 10.

**First affected release:** Unknown; this has been happening for a long time.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 119.0.6045.200
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 280 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002486) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks for the report, I think this is a regression from r330 when we first added support for multiple tags, and we missed this case. It should be fixed in the next beta.

**Comment by johnBrink** [comment]
Confirmed, this now works correctly on r371.
