### ISSUE TITLE
Flowchart: resizing cells can lead to broken visuals and unstable state

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7660]
## Problem description
resizing cells can lead to broken and unstable state

https://github.com/Scirra/Construct-bugs/assets/89512047/e6df88b0-8190-45f2-924e-19855989f63b

## Attach a .c3p
[flowchartScalingInterior.zip](https://github.com/Scirra/Construct-bugs/files/13684132/flowchartScalingInterior.zip)

## Steps to reproduce

1. move the left edge of the name cell

## Observed result
either ugly broken cells or sometimes broken state leading to crash (crash message below)

## Expected result
only transforms in the allowed range and no crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r371/main.js, line 1872, col 254
Message: Uncaught TypeError: Cannot read properties of null (reading 'vca')
Stack: TypeError: Cannot read properties of null (reading 'vca') at Ii.g.J.Table.MY.Up (https://editor.construct.net/r371/main.js:1872:254) at Ii.g.J.Table.MY.Ah (https://editor.construct.net/r371/main.js:1868:159) at Kia (https://editor.construct.net/r371/main.js:412:148) at CCG.ui.g.J.Table.l (https://editor.construct.net/r371/main.js:1846:308) at window.d3.l (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:46:343) at Mjb (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:23:443) at mkb.ic (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:94:264) at window.mq.Nga (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:35:124) at window.TWb.CS (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:72:239) at Array. (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:71:250)
Construct version: r371
URL: https://editor.construct.net/r371/
Date: Fri Dec 15 2023 11:26:24 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 31.6 s

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 120.0.6099.72
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
