### ISSUE TITLE
Editing css on android app causes crash.

### ISSUE THREAD

**Issue by OrcusLabs** [Scirra/Construct-bugs#7838]
## Problem description
Adding a dash to css line causes the line to be erased. Pasting with a dash can cause android app to crash.

This is the only project so far it happens in.

https://drive.google.com/file/d/1Cp3228K-1BOIW7_hQgw8Bk7GRTtJT963/view?usp=drivesdk

## Steps to reproduce
In hacking.css try to add font- to log-viewer.
Try pasting font-size.

1.
2.
3.

## Observed result

Typing font- in the css for log-viewer will erase that line.
Pasting font-size will often cause the app to crash.

## Expected result

Not crash.
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled exception
File: https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js, line 44, col 330
Message: Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')
Stack: TypeError: Cannot read properties of null (reading 'replaceChild') at cd (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:44:330) at Xg (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:113:224) at Me (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:109:386) at https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:97:445 at Rd (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:43:301) at tc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:96:168) at https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:104:58 at Oc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:142:431) at Pc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:149:87) at Fa.pollContent (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:289:409)
Construct version: r379
URL: https://editor.construct.net/
Date: Fri Feb 16 2024 13:57:59 GMT-0700 (Mountain Standard Time)
Uptime: 154.7 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.144
Browser engine: Chromium
Context: webapp
Operating system: Android 14.0.0
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Qualcomm)
Renderer: ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_clip_cull_distance, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by WilsonPercival** [comment]
Your link is closed.

**Comment by OrcusLabs** [comment]
> Your link is closed.

Found the real problem I think. Edited and new c3p uploaded. Should be available. Let me know if it isnt

**Comment by OrcusLabs** [comment]
This error was found as a result of using chat gpt to create the css which comments heavily.

**Comment by WilsonPercival** [comment]
After I press Enter I will not be able to type characters. I print and they get erased.

**Comment by OrcusLabs** [comment]
Tested in desktop client. Works as expected.

**Comment by AshleyScirra** [comment]
Spent a while looking in to this and just could not figure anything out at all unfortunately. I've no idea whether this is a browser bug, CodeMirror bug, or Construct bug, and I'm not sure what to do to further investigate at this point.

**Comment by AshleyScirra** [comment]
Since this issue was filed we've completely replaced CodeMirror with Monaco for the code editor, so this issue is most likely no longer applicable, so closing. If you still have trouble with the latest release please file a new issue.
