### ISSUE TITLE
Timeline and Hierarchies on SaveGame Critical Bug

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-bugs#7883]
## Problem description

In this case the element is added as a child and is destroyed while a timeline is running, at the same time we use the Save Game action, when we load the game, the destroyed objects loose their original values (their position is lost, their conditions are lost as well). Is like a zombie object that can even loose the capacity of detecting collisions some times.

This is part of a bigger bug that causes a Load Game to glitch the entire game, causing things like broken sounds, missing objects, objects loosing the collision capacity, etc... but im not capable to reproduce in small example. So i start with this zombie object bug.

 

## Attach a .c3p
https://drive.google.com/file/d/1QxbDlmGRmt8NbL3-GfDkLggrKDudCWoC/view?usp=sharing

## Steps to reproduce
Play the proyect, before the timeline ends, click on save, then click on load.

## Observed result
1. The child object is not destroying their parent
2. The child object is back once the load game is completed but glitched

## Expected result

1. The child object should be destroyed
3. The child object destroyed, shouldn't come back to life after load

## More details
![image](https://github.com/Scirra/Construct-bugs/assets/6506303/a16c5a53-d5d1-48fb-8ea0-ee338000a138)

**Affected browsers/platforms:** Chrome

**First affected release:** not sure, having this issue from several stable versions before

## System details

Error basic:
runtime.js:118 [Construct] Failed to load state from storage:  TypeError: Cannot read properties of undefined (reading 'uid')
    at Instance.LoadFromJson (instance.js:33:218)
    at SceneGraphInfo._CreateNewChildInstance (sceneGraphInfo.js:20:24)
    at SceneGraphInfo._OnAfterLoad (sceneGraphInfo.js:17:302)
    at WorldInfo._OnAfterLoad (worldInfo.js:77:201)
    at Instance._OnAfterLoad (instance.js:32:397)
    at C3Runtime.DoAfterLoad (runtime.js:128:352)
    at C3Runtime._DoLoadFromJsonString (runtime.js:126:469)
    at C3Runtime._DoLoadFromSlot (runtime.js:118:311)
    at async C3Runtime._HandleSaveOrLoad (runtime.js:115:52)
    at async C3Runtime.Tick (runtime.js:84:275)

error with big projects:
runtime.js:119 [Construct] Failed to load state from storage:  RangeError: invalid instance variable index
    at ObjectClass.GetInstanceVariableName (objectClass.js:17:216)
    at Track.propertyTrackItems (trackState.js:10:349)
    at propertyTrackItems.next (<anonymous>)
    at Track.SetInstance (trackState.js:7:357)
    at Timeline.SetTrackInstance (timelineState.js:34:177)
    at Track._LoadInstanceFromJson (trackState.js:32:278)
    at Track._LoadFromJson (trackState.js:30:76)
    at timelineState.js:40:155
    at Array.forEach (<anonymous>)
    at Timeline._LoadTracksFromJson (timelineState.js:40:97)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Instances in a hierarchy destroyed in the same tick as a save action were incorrectly saved, so trying to load that save game afterwards would run into all kinds of problems.
