### ISSUE TITLE
Physics Exception: Cannot read properties of null (reading 'GetContactList')

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8114]
## Problem description

The project is a physics-based car game. In Car.OnCreated, it initializes the joints. It was working a few weeks ago, but now it throws an exception:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetContactList')
    at PhysicsInstance._SetFriction (runtime.js:65:11)
    at PhysicsInstance.SetFriction (runtime.js:85:516)
    at Action._RunBehavior (action.js:35:230)
    at EventBlock._RunActions_Fast (eventBlock.js:26:466)
    at EventBlock._RunAndBlock (eventBlock.js:25:88)
    at EventBlock.Run (eventBlock.js:22:11)
    at EventBlock._RunSubEvents_SolWriterAfterCnds (eventBlock.js:31:3)
    at EventBlock._RunSubEvents (eventBlock.js:29:437)
    at EventBlock._RunAndBlock (eventBlock.js:25:114)
    at EventBlock.RunAsFunctionCall (eventBlock.js:40:6)
```

## Attach a .c3p
(sent in email for confidentiality)

## Steps to reproduce

1. Run the Game layout
2. (Disabling the Car.Initialize action will make the game work, but the car will be broken and have no joints)

## Observed result

Black screen, and red exception in the browser console.

## Expected result

Game plays normally.

## More details

**First affected release:** (It was working 3 months ago when the project was tested and delivered)

**Comment by AshleyScirra** [comment]
Minimal repro: [issue8114.zip](https://github.com/user-attachments/files/16236259/issue8114.zip)

**Comment by AshleyScirra** [comment]
Fixed for the next beta.
