### ISSUE TITLE
ISDKInstanceBase._getDebuggerProperties in SingleGlobal plugins throw an exception

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8152]
## Problem description

Method ISDKInstanceBase._getDebuggerProperties fails execute to dislpay debugger properties in SingleGlobal plugins.

## Attach a .c3p

Just add the attached addon to aproject, taken from the SDK sample template, then run the projet in debug mode.
[mycompany_singleglobal.zip](https://github.com/user-attachments/files/16490702/mycompany_singleglobal.zip)

## Steps to reproduce

1. Install the attached addon
2. Create a blak project and add the plugin to it
3. Run the layout in debug mode
4. Select the addon in the debug properties and the exception will be thrown
![image](https://github.com/user-attachments/assets/a0f83514-4fff-47d5-aa31-277bf3b112af)

![image](https://github.com/user-attachments/assets/b8be11a8-522d-47d2-a687-82f01acc9932)
## Observed result

Exception is thrown.

## Expected result

It should run with no exceptions thrown,.

## More details
Construct r401 beta
## System details

<details><summary>View details</summary>

runtime.js:19 Exception in 'debugger' handler 'message': TypeError: this._iScriptInterface.getDebuggerProperties is not a function
    at Instance._GetDebuggerProperties (instance.js:33:36)
    at C3Debugger._GetInstanceInspectData (previewOnly.js:39:171)
    at C3Debugger._UpdateInspectInstanceData (previewOnly.js:40:106)
    at C3Debugger._UpdateDebugViewData (previewOnly.js:20:193)
    at C3Debugger._OnInspectInstance (previewOnly.js:19:264)
    at C3Debugger._OnMessageFromDebugger (previewOnly.js:7:253)
    at previewOnly.js:6:109
    at C3Runtime._OnEventFromDOM (runtime.js:19:29)
    at C3Runtime._OnMessageFromDOM (runtime.js:16:289)
    at C3Runtime._messagePort.onmessage (runtime.js:12:152)
_OnEventFromDOM @ runtime.js:19Understand this error
45instance.js:33 Uncaught TypeError: this._iScriptInterface.getDebuggerProperties is not a function
    at Instance._GetDebuggerProperties (instance.js:33:36)
    at C3Debugger._GetInstanceInspectData (previewOnly.js:39:171)
    at C3Debugger._UpdateInspectInstanceData (previewOnly.js:40:106)
    at C3Debugger._UpdateDebugViewData (previewOnly.js:20:193)
    at previewOnly.js:5:144Understand this error
792instance.js:33 Uncaught TypeError: this._iScriptInterface.getDebuggerProperties is not a function
    at Instance._GetDebuggerProperties (instance.js:33:36)
    at C3Debugger._GetInstanceInspectData (previewOnly.js:39:171)
    at C3Debugger._UpdateInspectInstanceData (previewOnly.js:40:106)
    at C3Debugger._UpdateDebugViewData (previewOnly.js:20:193)
    at previewOnly.js:5:144

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
