### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 folder project. (After clearing cache)

### ISSUE THREAD

**Issue by saltandpixel** [Scirra/Construct-bugs#8222]
## Problem description

Construct won't open any file of this game, in stable or beta.

main.js:907 [Project] Exception opening:  Error: missing condition id 'compare-z-elevation'
    at window.tpb.tW (projectResources.js:1622:37)
    at window.Qga.tW (main.js:2587:188)
    at d.LE (projectResources.js:1571:341)
    at d.za (projectResources.js:1533:442)
    at window.nW.F$b (projectResources.js:1489:373)
    at d.pAb (projectResources.js:1498:104)
    at d.za (projectResources.js:1534:10)
    at window.nW.F$b (projectResources.js:1489:373)
    at d.pAb (projectResources.js:1498:104)
    at d.za (projectResources.js:1534:10)
    
    I keep getting this error for every version of my game and back ups, r397 and up. which is weird, because it was opening fine all day when I was troubleshooting another error.

## Attach a .c3p

latest beta version r406.2

link: https://drive.google.com/file/d/1zTA4JjE_MGJDHQmGk_YQW5Uj76ylgMOs/view?usp=sharing

## Steps to reproduce

Here's how I got to this point.
- I update my project from r397 to r406 not realizing it was a beta.
- Went to export a NWJS, and the game crashes on launch.
- Convert files back to r397.
- everything works fine in the editor, export is goes well. Game launch successful, but 3DObjects don't load.
- Test htm5 export on itch, and the same issue appears 3Dobjects don't load.
- Revert back to previous html release, but the file is corrupted so I clear my cache. Previous html5 game works again.
- Bring setup C3 and install plugins and try to open and "compare-z-elevation" error. 
- I start downloading a testing previous version all the back to r397, and get this error.

## Observed result

error message.

## Expected result

File open in r406 or with better luck a stable version that I can start to rebuild from.

## More details

**Affected browsers/platforms:** 

Chrome
Firefox

**First affected release:** 
Worked in r397 and r406 before cleaning cache. Now works in neither.

## System details

<details><summary>Platform information
Product: Construct 3 r406.2 (beta)
Browser: Chrome 128.0.6613.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 109 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009BC4) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)</summary>

PASTE HERE

</details>

**Comment by saltandpixel** [comment]
Wanted to comment that I got the file to open on my tablet and the issue was related to the 3D Object plug-in. I removed all 3D objects and it opened on my PC.

**Comment by AshleyScirra** [comment]
The project uses many third-party addons:

```
Plugin 3D Object (Mikal_3DObject) by Mikal
Behavior Rapier 3D Physics (mikal_cannon_3d_physics) by Mikal
Behavior Rotate 3D (mikal_rotate_shape) by mikal
Behavior Radial Progress (skymen_RadialProgress) by skymen
Behavior sphere (spokoinbli_sphere) by spokoinbli
Effect Lottes CRT (Lottes) by Timothy Lottes / converted by Erik Thon
Effect MotionBlur (Mikal_MotionBlur) by Mikal
Effect Outline Glow (Mikal_OutlineGlow) by Mikal
Effect Screen Space 3D Lights (Mikal_SS3DLights) by Mikal
Effect Gradient (federicoCalchera_Gradient) by Federico Calchera
Effect Directional Blur (federicoCalchera_directionalBlur) by Federico Calchera
Effect Linear Gradient (lineargradient) by Ludonaut
```

I'm afraid as per the bug report guidelines we cannot provide support for such projects.

I think it's likely in this case to be a compatibility problem caused by a third-party addon. For example it may be that you saved the project using a condition "compare-z-elevation" in a third-party addon, then tried to open the project on a device with an older version of the addon installed which does not have that condition. That would cause this type of error message. However that is not a bug in Construct, the problem is that you would have used incompatible versions of third-party addons.

**Comment by saltandpixel** [comment]
That's what it was outdated 3D Objects Plug-in.
