### ISSUE TITLE
Personal: unable to debug layout, unable to reliably preview layout.

### ISSUE THREAD

**Issue by SCPTV** [Scirra/Construct-bugs#8310]
## Problem description

Unable to debug layout, unable to reliably preview layout.

I tried asking on the construct forums, but they directed me here instead. Because this has something to do with my computers you wont be able to replicate it, but I'm at the end of my rope with this issue. 

## Attach a .c3p

Because my issue is not project-specific, I doubt you will get anything out of this.

[Drive](https://drive.google.com/file/d/17EoxkKQdbvq5vAdkD9xTqdP8L5MMGhov/view?usp=drive_link)

## Steps to reproduce

Naturally, these steps will also not be helpful as they are specific to me.
1. Open any project
2. Select Debug Project, Debug Layout, etc.

## Observed result

White screen that says "Loading..." forever.

## Expected result

I expect to be able to debug my projects

## More details

I own two computers, a laptop and a workstation. On both of these i am unable to use debug layout on construct. This affects all projects, and different users. Because I am of low intellect, I cannot decode the error messages in the console, or how to fix them. This also affects preview project, but if I preview the project in the offline construct 3 editor, open the console via f12, then restart the layout with f5, it seems to work reliably. This does not work when I try to debug layout, which I am now simply unable to do. 

The most helpful thing I can attach is a video demonstrating the issue, this also shows the error messages I get. I will note that the error messages are often different depending on browser and computer, but the end result is always the same.

https://youtu.be/PS-HCqIN0Gg

**Affected browsers/platforms:**

All of them. I usually use the offline construct editor, but I have also tried on Edge and Firefox, with no luck.

**First affected release:**

I cannot say, I do not keep up to date on stuff like this. Would saying "the last few months" make any difference?

## System details

Platform information
Product: Construct 3 r407.2 (stable)
Browser: Edge 130.0.2849.56
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 91 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F08) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 1
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
<details><summary>View details</summary>

**Comment by Jase0000** [comment]
Hey there,

Weird it happens with multiple devices and browsers.

Do you use extensions in your browsers, especially privacy-based extensions (e.g. AdBlock)? 

Do you use any VPN software? (specifically, NordVPN can cause issues).

Do you install any antivirus software, privacy software, or networking software tools, on your devices? If you do, let us know which ones. 

Could you try opening a project on your mobile phone and try debug preview? (any of the C3 templates are fine). It might be unusable on phone BUT important to see if it at least loads correctly. 

If it also does not work on your mobile phone (and you don't use a vpn service), then it's might be your router (is it just standard router that your Internet provider gave to you? Did you reconfigure it?), or possibly your ISP.

**Comment by SCPTV** [comment]
Thanks for a quick reply. I do have NordVPN on all my devices. Tried uninstalling it, rebooted computer, debug is sadly still broken. I do not have any extensions on the Edge browser yet it is still broken, so I doubt that is the issue. I tried debug layout on my phone, same issue (somehow). A router issue then, perhaps? Connected to 4g via my phone: somehow, still broken. I cannot even provide a consistent console error message, although the most common one goes something along the lines of: 

"Uncaught TypeError: Cannot read properties of null (reading 'insertAdjacentHTML')
    at OnBoot (bootPreview.js:116:18)
    at OnBootMessage (bootPreview.js:51:4)"

and then, on f5 pressed: 

"GET https://preview.construct.net/Lcqg7fc7pNeT7m_L net::ERR_ABORTED 404 (Not Found)"

If it not an issue with the browser, user, computer or network? I can only conclude that the Construct gods have cursed me to be unable to debug my layouts ever again. I do appreciate your attempt to help though.

**Comment by AshleyScirra** [comment]
It works fine for me, and I'm not aware of many other customers having such issues at the moment, so it sounds a lot like a problem specific to your end and not an issue with Construct itself. The errors you showed indicate something other than Construct making network requests on Construct domains - a classic sign that browser extensions, security software, a VPN or some other piece of third party software is interfering with Construct and breaking it. I'm afraid it's difficult to say more than that. I would suggest checking what software you have installed, what your networking setup is, and try changing settings or removing software until the problem is corrected. You may need to clear your browser cache before it starts working again after fixing the problem, as it may continue loading stale broken content even after you fix the problem. If you identify the software or tool that's breaking Construct, please report it to the respective developer - we get a lot of such cases of other people's software breaking Construct and it's always a support headache for us.

**Comment by Jase0000** [comment]
@SCPTV I agree with Ashley that it doesn't seem like C3 issue, only because yeah, everyone else can use it fine!

Feel free to join the unofficial Construct Discord and write a message about this in "Offtopic", I will reach out and could try and help further (I can't promise I can solve it though and I'm not always available to help, but worth a shot!):

https://discord.gg/GVEk3P26

**Comment by SCPTV** [comment]
So I downloaded the Brave browser, and somehow, on that one I can debug and preview just fine. No idea how, since Edge and Brave are both chromium, and I have no extension on either the Edge or Brave browser, but whatever. If it works, it works. Thank you both for your insights, and I am sorry I couldn't isolate the problem for fixing.
